# Generated by Django 5.0.4 on 2024-04-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_type',
            field=models.CharField(choices=[('Start', 'Start'), ('Middle', 'Middle'), ('Finish', 'Finish')], default='Start', max_length=10),
        ),
    ]
