# Generated by Django 5.0.4 on 2024-04-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_comments_comment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_type',
            field=models.CharField(choices=[('start', 'Start'), ('middle', 'Middle'), ('finish', 'Finish'), ('updated_start', 'Updated Start')], default='start', max_length=220),
        ),
    ]
