# Generated by Django 5.0.4 on 2024-05-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Чоловік'), ('F', 'Жінка')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('english_level', models.CharField(choices=[('A1', 'Початковий рівень (A1)'), ('A2', 'Елементарний рівень (A2)'), ('B1', 'Середній рівень (B1)'), ('B2', 'Високий рівень (B2)'), ('C1', 'Досконалий рівень (C1)'), ('C2', 'Високий досконалий рівень (C2)')], max_length=2)),
            ],
        ),
    ]
